#!/bin/bash
#
# Author(s):  smashingtags  
# URL:        https://github.com/MHA-Team - https://github.com/RandomNinjaAtk/docker-amd
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'docker-amd'
        intport: '8686'
        extport: '8686'
        image: 'randomninjaatk/amd'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/communityapps/apps/_core.yml'

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}}{{tldset}}{{cname}}'
          traefik.frontend.headers.SSLHost: '{{domain.stdout}}'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'

    - name: 'Setting {{pgrole}} Volumes'
      set_fact:
        pg_volumes:
          - '/opt/appdata/{{pgrole}}:/root/config'
          - '/opt/appdata/{{pgrole}}:/root/downloads-amd'

    - name: 'Setting {{pgrole}} ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'
          TZ: 'America/New_York'
          UMASK_SET: '22'
          AUTOSTART: 'true
          SCRIPTINTERVAL: 1h
          DOWNLOADMODE: wanted
          FALLBACKSEARCH: True
          LIST: both
          SearchType: both'
          Concurrency: '1'
          EMBEDDED_COVER_QUALITY: '80'
          FORMAT: 'FLAC'
          BITRATE: '320'
          ENABLEPOSTPROCESSING: 'true'
          FORCECONVERT: 'false'
          requirequality: 'false'
          MatchDistance: '10'
          replaygain: 'true'
          FolderPermissions: '766'
          FilePermissions: '666'
          MBRAINZMIRROR: 'https://musicbrainz.org'
          MBRATELIMIT: '1'
          LidarrUrl: 'http://x.x.x.x:8686'
          LidarrAPIkey: 'LIDARRAPI'
          ARL_TOKEN: 'ARLTOKEN'
          NOTIFYPLEX: 'false'
          PLEXLIBRARYNAME: 'Music'
          PLEXURL: 'http://x.x.x.x:8686'
          PLEXTOKEN: 'plextoken'
          ALBUM_TYPE_FILTER: 'COMPILE'
          POSTPROCESSTHREADS: '1'
  

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'          
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'
